title: Minimalistic theme
logo: /assets/img/logo.png
description: Minimalistic is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimalistic

platforms:
  - name: GitHub
    link: https://github.com/vaibhavvikas

navigation:
  - name: Readme
    link: ./readme.html
    sublist:
      - name: Usage
        link: ./readme.html#usage
  - name: GitHub
    link: https://github.com/vaibhavvikas
