title:     M-A-C
logo: /assets/img/AvatarMac.png
#email: person@address.com
description:      My Arch Linux and Security Documentation and more

favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
   # name: LinkedIn
   # icon: <i class="fa-brands fa-linkedin"></i>
   # link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: What's this about
    link: ./index.html
    #sublist:
    #  - name: Image
    #    link: ./index.html#small-image
  - name: PCEP_Python_Institute
    link: ./PCEP_Python_Institute.html
    sublist:
      - name: Operators and Expressions
        link: ./PCEP_Python_Institute.html#operators-and-expressions
      - name: Break and Continue
        link: ./PCEP_Python_Institute.html#break-and-continue
      - name: The Ugly Vowel Eater
        link: ./PCEP_Python_Institute.html#the-continue-statement-the-ugly-vowel-eater
  - name: CTF
    link: ./ctf.html
    sublist:
      - name: BufferOverflow1
        link: ./ctf.html#bufferoverflow1
  - name: How_to_use_this_theme
    link: ./How_to_use_this_theme.html
    
