title:     M-A-C
logo: /assets/img/avatarID.jpg
#email: person@address.com
description:      CEH | CCNA | RHCE

favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/0ffmac
   # name: LinkedIn
   # icon: <i class="fa-brands fa-linkedin"></i>
   # link: https://www.linkedin.com/in/miquelarenyas

navigation:
  - name: What's this about
    link: ./index.html
  - name: HackTheBox-Machines
    link: ./htb.html
    sublist:
      - name: Soccer
        link: ./htb.html#soccer
      - name: Broscience
        link: ./htb.html#broscience
      - name: Mentor
        link: ./htb.html#mentor
  - name: PCEP_Python_Institute
    link: ./PCEP_Python_Institute.html
    sublist:
      - name: Operators and Expressions
        link: ./PCEP_Python_Institute.html#operators-and-expressions
      - name: Break and Continue
        link: ./PCEP_Python_Institute.html#break-and-continue
      - name: The Ugly Vowel Eater
        link: ./PCEP_Python_Institute.html#the-continue-statement-the-ugly-vowel-eater
  - name: CTF
    link: ./ctf.html
    sublist:
      - name: BufferOverflow1
        link: ./ctf.html#bufferoverflow1
      - name: BufferOverflow2
        link: ./ctf.html#bufferoverflow2
  - name: How_to_use_this_theme
    link: ./How_to_use_this_theme.html
    
